# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0394fda3cfd558b1cbbe1d4373a47efcbe59c6d666b436d956405633ad251daaf5c0870aca13db7ad6d5c4febaee237d9f9da0dcc18ba69a413d2015d187d886

test:
  secret_key_base: 0593482e556f6f8fff1ce759b99d0a720a0a1bafca11c9113ec0da61aac6b39e35441bce42bac743def6ffe07117cef594361b484fa2a65e8e6f3a82e9c34a4d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
